"""Instruction counts and DMA spill queues of compiled graphs, read from their NEFFs in LNL's compile
cache (kiln/compile_cache.py local_dir: <root>/neuron/compile_cache/<hash>/graph_<hash>.neff).

    python tools/neff_instructions.py <cache dir> [...]      # one line per graph
    python tools/neff_instructions.py --latest 4             # the 4 most recently written entries

A NEFF is a 1024-byte header plus a tar.gz; sg00/<engine>0.bin is each engine's instruction stream
at 64 bytes per instruction (Activation, DVE, PE, Pool, SP), the count neuronx-cc's 5 M limit is
about ("NCC_EBVF030 Instructions generated by compiler N exceeds the typical limit", the prefill
MoE notes in docs/neuron-notes.md count the same way). Spill queues: the DMA entries of
sg00/<engine>.json whose queue name holds "Spill" and the contiguous runs they move, which is what the
runtime's "dma rings spill" grows with (tools/neff_info.py on feat/compile-farm, the same parse).
"""

from __future__ import annotations

import io
import json
import os
import re
import sys
import tarfile

BYTES_PER_INSTRUCTION = 64


def cache_root() -> str:
    root = os.environ.get("NEURON_LIBTORCH_CACHE_ROOT", os.path.expanduser("~/.cache/neuron_libtorch"))
    return os.path.join(root, "neuron", "compile_cache")


def _runs(c: dict) -> int:
    def side(sizes):
        n = 1
        for s in (sizes or [1])[1:]:
            n *= int(s)
        return n

    return max(side(c.get("from_sizes")), side(c.get("to_sizes")))


def summary(entry: str) -> dict:
    """{engine: instructions, total, spill_entries, spill_runs} of one cache entry directory."""
    key = os.path.basename(entry.rstrip("/"))
    neff = os.path.join(entry, f"graph_{key}.neff")
    with open(neff, "rb") as f:
        f.seek(1024)
        data = f.read()
    out: dict = {"key": key}
    spill_e = spill_r = 0
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as t:
        for m in t.getmembers():
            b = re.search(r"sg\d+/([A-Za-z]+)\d+\.bin$", m.name)
            if b:
                out[b.group(1)] = out.get(b.group(1), 0) + m.size // BYTES_PER_INSTRUCTION
            if re.search(r"sg\d+/[A-Za-z]+\d+\.json$", m.name):
                for e in json.load(t.extractfile(m)).get("dma") or []:
                    if "Spill" in str(e.get("queue", "")):
                        spill_e += 1
                        spill_r += sum(_runs(c) for c in e.get("desc") or [])
    out["total"] = sum(v for k, v in out.items() if k != "key")
    out["spill_entries"], out["spill_runs"] = spill_e, spill_r
    return out


def latest(n: int = 1, since: float = 0.0) -> list[str]:
    """The n most recently written complete cache entries (written at or after `since`)."""
    root = cache_root()
    if not os.path.isdir(root):
        return []
    ds = []
    for d in os.listdir(root):
        p = os.path.join(root, d)
        neff = os.path.join(p, f"graph_{d}.neff")
        if os.path.exists(neff) and os.path.getmtime(neff) >= since:
            ds.append((os.path.getmtime(neff), p))
    return [p for _, p in sorted(ds, reverse=True)[:n]]


def line(entry: str) -> str:
    s = summary(entry)
    eng = ", ".join(f"{k} {v:,}" for k, v in s.items() if k not in ("key", "total", "spill_entries", "spill_runs"))
    return (f"instructions {s['total']:,} ({eng}); spill DMA entries {s['spill_entries']:,}, runs {s['spill_runs']:,} "
            f"[{s['key'][:12]}]")


def main() -> None:
    args = sys.argv[1:]
    if args[:1] == ["--latest"]:
        args = latest(int(args[1]) if len(args) > 1 else 1)
    for a in args:
        print(line(a), flush=True)


if __name__ == "__main__":
    main()
